'use client';

import { useEffect, useMemo, useState } from 'react';
import { PackagePlus, Trash2, RefreshCw, ShoppingCart, Boxes, Plus, Save, Pencil, X } from 'lucide-react';

type Product = { id:string; name:string; description?:string; category:string; categoryId?:string; sku?:string; imageUrl?:string; price:number; cost:number; stock:number; lowStockThreshold:number; active:boolean };
type Category = { id:string; name:string; description?:string };
type Order = { id:string; customer:string; phone:string; address:string; items:any[]; total:number; status:string; createdAt:string };

const emptyForm = { id:'', name:'', description:'', categoryId:'', price:'', cost:'', stock:'', lowStockThreshold:'3', sku:'', imageUrl:'' };

export default function Dashboard(){
 const [products,setProducts]=useState<Product[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [tab,setTab]=useState('products'); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
 const [form,setForm]=useState(emptyForm); const [cat,setCat]=useState(''); const [editingCat,setEditingCat]=useState<string|null>(null); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/store',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'تعذر تحميل البيانات');setProducts(d.products||[]);setCategories(d.categories||[]);setOrders(d.orders||[])}catch(e){setError(e instanceof Error?e.message:'حصل خطأ')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!form.categoryId&&categories[0]?.id)setForm(f=>({...f,categoryId:categories[0].id}))},[categories,form.categoryId]);
 const saveProduct=async()=>{if(!form.name.trim()||!form.price)return;setSaving(true);setError('');try{const r=await fetch('/api/store',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'product',id:form.id||undefined,name:form.name,description:form.description,categoryId:form.categoryId,category:categories.find(c=>c.id===form.categoryId)?.name||'عام',price:form.price,cost:form.cost,stock:form.stock,lowStockThreshold:form.lowStockThreshold,sku:form.sku,imageUrl:form.imageUrl})});const d=await r.json();if(!r.ok)throw new Error(d.error||'فشل الحفظ');setForm({...emptyForm,categoryId:categories[0]?.id||''});await load()}catch(e){setError(e instanceof Error?e.message:'فشل الحفظ')}finally{setSaving(false)}};
 const editProduct=(p:Product)=>setForm({id:p.id,name:p.name,description:p.description||'',categoryId:p.categoryId||categories.find(c=>c.name===p.category)?.id||'',price:String(p.price),cost:String(p.cost),stock:String(p.stock),lowStockThreshold:String(p.lowStockThreshold??3),sku:p.sku||'',imageUrl:p.imageUrl||''});
 const remove=async(id:string)=>{if(!confirm('حذف المنتج؟'))return;const r=await fetch('/api/store',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'deleteProduct',id})});if(!r.ok){const d=await r.json();setError(d.error||'فشل الحذف');return}load()};
 const addCategory=async()=>{if(!cat.trim())return;const r=await fetch('/api/store',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'category',id:editingCat||undefined,name:cat})});const d=await r.json();if(!r.ok){setError(d.error||'فشل حفظ التصنيف');return}setCat('');setEditingCat(null);load()};
 const deleteCategory=async(id:string)=>{if(!confirm('حذف التصنيف؟'))return;const r=await fetch('/api/store',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'deleteCategory',id})});const d=await r.json();if(!r.ok){setError(d.error||'لا يمكن حذف التصنيف');return}load()};
 const revenue=useMemo(()=>orders.reduce((s,o)=>s+Number(o.total||0),0),[orders]);
 const statusLabel=(s:string)=>({new:'جديد',confirmed:'مؤكد',processing:'قيد التجهيز',shipped:'تم الشحن',delivered:'تم التسليم',cancelled:'ملغي'} as any)[s]||s;
 return <main dir="rtl" style={{minHeight:'100vh',background:'#f7f6f2',color:'#111',padding:'28px',fontFamily:'Arial,sans-serif'}}><div style={{maxWidth:1200,margin:'auto'}}>
  <header style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:24}}><div><div style={{fontSize:13,color:'#777'}}>FlowSell AI</div><h1 style={{margin:'4px 0',fontSize:34}}>لوحة التحكم</h1><div style={{color:'#777'}}>إدارة المنتجات والمخزون والطلبات</div></div><button onClick={load} style={btn}><RefreshCw size={16}/> تحديث</button></header>
  {error&&<div style={{...card,marginBottom:14,borderColor:'#e66',color:'#a00'}}>{error}</div>}
  <section style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginBottom:20}}>{[[products.length,'المنتجات',Boxes],[products.reduce((s,p)=>s+p.stock,0),'إجمالي المخزون',PackagePlus],[orders.length,'الطلبات',ShoppingCart],[revenue.toLocaleString('ar-EG')+' ج','المبيعات',ShoppingCart]].map(([v,t,I]:any)=><div style={card} key={t}><I size={19}/><span style={{color:'#777',fontSize:13,display:'block',marginTop:8}}>{t}</span><b style={{fontSize:25,display:'block',marginTop:5}}>{v}</b></div>)}</section>
  <nav style={{display:'flex',gap:8,marginBottom:16}}>{[['products','المنتجات'],['orders','الطلبات'],['categories','التصنيفات']].map(([k,t])=><button key={k} onClick={()=>setTab(k)} style={{...btn,background:tab===k?'#111':'#fff',color:tab===k?'#fff':'#111'}}>{t}</button>)}</nav>
  {tab==='products'&&<>
   <section style={{...card,marginBottom:16}}><div style={{display:'flex',justifyContent:'space-between'}}><h3 style={{marginTop:0}}>{form.id?'تعديل منتج':'إضافة منتج'}</h3>{form.id&&<button onClick={()=>setForm({...emptyForm,categoryId:categories[0]?.id||''})} style={btn}><X size={15}/> إلغاء</button>}</div><div style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr 1fr',gap:8}}>{[['name','اسم المنتج'],['price','سعر البيع'],['cost','سعر الشراء'],['stock','المخزون'],['sku','SKU']].map(([k,p])=><input key={k} placeholder={p} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} style={input}/>)}<select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})} style={input}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input placeholder="حد المخزون المنخفض" value={form.lowStockThreshold} onChange={e=>setForm({...form,lowStockThreshold:e.target.value})} style={input}/><input placeholder="رابط الصورة" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})} style={input}/><textarea placeholder="الوصف" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} style={{...input,minHeight:42}}/><button disabled={saving} onClick={saveProduct} style={darkBtn}><Save size={16}/> {saving?'جاري الحفظ':'حفظ'}</button></div></section>
   <section style={card}>{loading?'جاري التحميل...':<table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={th}>المنتج</th><th style={th}>التصنيف</th><th style={th}>البيع</th><th style={th}>الشراء</th><th style={th}>المخزون</th><th style={th}>الحالة</th><th style={th}></th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td style={td}><b>{p.name}</b><div style={{fontSize:12,color:'#888'}}>{p.sku}</div></td><td style={td}>{p.category}</td><td style={td}>{Number(p.price).toLocaleString('ar-EG')} ج</td><td style={td}>{Number(p.cost).toLocaleString('ar-EG')} ج</td><td style={td}><b>{p.stock}</b>{p.stock<=p.lowStockThreshold&&<small style={{color:'#a60',display:'block'}}>مخزون منخفض</small>}</td><td style={td}>{p.active?'نشط':'غير نشط'}</td><td style={{...td,whiteSpace:'nowrap'}}><button onClick={()=>editProduct(p)} style={iconBtn}><Pencil size={16}/></button><button onClick={()=>remove(p.id)} style={{...iconBtn,color:'#b00'}}><Trash2 size={16}/></button></td></tr>)}</tbody></table>}</section>
  </>}
  {tab==='orders'&&<section style={card}><h3 style={{marginTop:0}}>الطلبات</h3>{orders.length===0?<div style={{color:'#888'}}>لسه مفيش طلبات.</div>:orders.map(o=><div key={o.id} style={{borderBottom:'1px solid #eee',padding:'14px 0',display:'flex',justifyContent:'space-between',gap:12}}><div><b>{o.customer}</b><div style={{color:'#777',fontSize:13}}>{o.phone} • {o.address}</div><div style={{fontSize:12,color:'#777',marginTop:5}}>{o.items?.map((i:any)=>`${i.name} × ${i.qty}`).join('، ')}</div></div><div style={{textAlign:'left',minWidth:150}}><b>{Number(o.total).toLocaleString('ar-EG')} ج</b><select value={o.status} onChange={async e=>{const status=e.target.value;const r=await fetch('/api/store',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'orderStatus',id:o.id,status})});if(r.ok)setOrders(x=>x.map(v=>v.id===o.id?{...v,status}:v));else setError('فشل تحديث حالة الطلب')}} style={{...input,marginTop:6}}><option value="new">جديد</option><option value="confirmed">مؤكد</option><option value="processing">قيد التجهيز</option><option value="shipped">تم الشحن</option><option value="delivered">تم التسليم</option><option value="cancelled">ملغي</option></select><div style={{fontSize:11,color:'#777',marginTop:4}}>{statusLabel(o.status)}</div></div></div>)}</section>}
  {tab==='categories'&&<section style={card}><h3 style={{marginTop:0}}>التصنيفات</h3><div style={{display:'flex',gap:8,marginBottom:16}}><input value={cat} onChange={e=>setCat(e.target.value)} placeholder="اسم التصنيف" style={{...input,maxWidth:300}}/><button onClick={addCategory} style={darkBtn}><Plus size={16}/> {editingCat?'حفظ التعديل':'إضافة'}</button>{editingCat&&<button onClick={()=>{setEditingCat(null);setCat('')}} style={btn}>إلغاء</button>}</div><div style={{display:'grid',gap:8}}>{categories.map(c=><div key={c.id} style={{padding:'10px 12px',background:'#eee',borderRadius:12,display:'flex',justifyContent:'space-between',alignItems:'center'}}><span>{c.name}</span><span><button onClick={()=>{setEditingCat(c.id);setCat(c.name)}} style={iconBtn}><Pencil size={15}/></button><button onClick={()=>deleteCategory(c.id)} style={{...iconBtn,color:'#b00'}}><Trash2 size={15}/></button></span></div>)}</div></section>}
 </div></main>
}
const card:any={background:'#fff',border:'1px solid #e6e4de',borderRadius:16,padding:18,boxShadow:'0 4px 18px rgba(0,0,0,.03)'}; const btn:any={border:'1px solid #ddd',background:'#fff',borderRadius:10,padding:'10px 14px',display:'inline-flex',gap:7,alignItems:'center',cursor:'pointer'}; const darkBtn:any={...btn,background:'#111',color:'#fff',borderColor:'#111'}; const input:any={border:'1px solid #ddd',borderRadius:9,padding:'11px',outline:'none',minWidth:0}; const th:any={textAlign:'right',padding:'10px',borderBottom:'1px solid #eee',color:'#777',fontSize:13}; const td:any={textAlign:'right',padding:'12px 10px',borderBottom:'1px solid #f0efeb'}; const iconBtn:any={border:0,background:'transparent',cursor:'pointer',padding:6};
