'use client';
import { useEffect, useState } from 'react';
import { Send, ShoppingCart, Bot } from 'lucide-react';

export default function Assistant(){
 const [products,setProducts]=useState<any[]>([]),[messages,setMessages]=useState<any[]>([{role:'assistant',content:'أهلًا 👋 أنا موظف مبيعات FlowSell. اسألني عن أي منتج، السعر، التوفر أو التوصيل.'}]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[customer,setCustomer]=useState({name:'',phone:'',address:''}),[cart,setCart]=useState<any[]>([]),[notice,setNotice]=useState('');
 const load=async()=>{try{const r=await fetch('/api/store',{cache:'no-store'});const d=await r.json();setProducts(d.products||[])}catch{}};
 useEffect(()=>{load()},[]);
 const send=async()=>{if(!text.trim()||busy)return;const value=text.trim();setText('');setMessages(m=>[...m,{role:'user',content:value}]);setBusy(true);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:value,products,history:messages.slice(-8)})});const d=await r.json();setMessages(m=>[...m,{role:'assistant',content:d.reply||'حاول تاني من فضلك.'}])}catch{setMessages(m=>[...m,{role:'assistant',content:'حصلت مشكلة بسيطة، جرّب تاني.'}])}finally{setBusy(false)}};
 const add=(p:any)=>{if(p.stock<=0)return;setNotice('');setCart(c=>{const old=c.find(x=>x.productId===p.id);if(old&&old.qty>=p.stock)return c;return old?c.map(x=>x.productId===p.id?{...x,qty:x.qty+1}:x):[...c,{productId:p.id,name:p.name,price:p.price,qty:1}]})};
 const changeQty=(id:string,delta:number)=>setCart(c=>c.map(x=>{if(x.productId!==id)return x;const p=products.find(y=>y.id===id);return {...x,qty:Math.max(0,Math.min(Number(p?.stock||999999),x.qty+delta))}}).filter(x=>x.qty>0));
 const total=cart.reduce((s,x)=>s+x.price*x.qty,0);
 const order=async()=>{if(!customer.name||!customer.phone||!customer.address||!cart.length){setNotice('اكتب الاسم والموبايل والعنوان واختار منتج.');return}setNotice('جاري تأكيد الطلب...');try{const r=await fetch('/api/store',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'order',customer:customer.name,phone:customer.phone,address:customer.address,items:cart.map(x=>({productId:x.productId,qty:x.qty}))})});const d=await r.json();if(d.ok){const confirmedTotal=Number(d.order?.total||0);setCart([]);setNotice('تم تسجيل الطلب بنجاح ✅');setMessages(m=>[...m,{role:'assistant',content:`تمام يا ${customer.name} ❤️ طلبك اتسجل بإجمالي ${confirmedTotal.toLocaleString('ar-EG')} جنيه. هنراجع البيانات ونتواصل معاك.`}]);await load()}else setNotice(d.error||'حصلت مشكلة في تسجيل الطلب.')}catch{setNotice('تعذر الاتصال بالسيرفر، جرّب تاني.')}};
 return <main dir="rtl" style={{minHeight:'100vh',background:'#f6f5f1',padding:24,fontFamily:'Arial'}}><div style={{maxWidth:1100,margin:'auto'}}><header style={{marginBottom:20}}><div style={{color:'#777',fontSize:13}}>FlowSell AI</div><h1 style={{margin:'5px 0'}}>موظف المبيعات الذكي</h1><p style={{color:'#777'}}>بيانات حقيقية من كتالوج المتجر + تسجيل طلبات.</p></header><div style={{display:'grid',gridTemplateColumns:'1.5fr 1fr',gap:16}}>
 <section style={panel}><div style={{display:'flex',gap:10,alignItems:'center',borderBottom:'1px solid #eee',paddingBottom:12}}><Bot/><b>FlowSell AI</b></div><div style={{height:460,overflow:'auto',padding:'18px 4px'}}>{messages.map((m,i)=><div key={i} style={{display:'flex',justifyContent:m.role==='user'?'flex-start':'flex-end',margin:'10px 0'}}><div style={{maxWidth:'80%',padding:'11px 14px',borderRadius:14,background:m.role==='user'?'#111':'#eeeee8',color:m.role==='user'?'#fff':'#111'}}>{m.content}</div></div>)}{busy&&<div style={{color:'#888',fontSize:13}}>المساعد بيكتب...</div>}</div><div style={{display:'flex',gap:8}}><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="اكتب رسالة..." style={input}/><button onClick={send} disabled={busy} style={dark}><Send size={17}/></button></div></section>
 <aside><section style={panel}><h3>المنتجات المتاحة</h3>{products.filter(p=>p.active!==false).map(p=><div key={p.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'10px 0',borderBottom:'1px solid #eee'}}><div><b>{p.name}</b><div style={{fontSize:12,color:'#777'}}>{Number(p.price).toLocaleString('ar-EG')} ج • المخزون {p.stock}</div></div><button disabled={!p.stock} onClick={()=>add(p)} style={dark}><ShoppingCart size={15}/></button></div>)}</section><section style={{...panel,marginTop:16}}><h3>إتمام الطلب {cart.length>0&&`(${cart.length})`}</h3>{cart.map(x=><div key={x.productId} style={{display:'flex',justifyContent:'space-between',alignItems:'center',fontSize:13,margin:'7px 0'}}><span>{x.name} × {x.qty}</span><span><button onClick={()=>changeQty(x.productId,-1)} style={qty}>−</button><button onClick={()=>changeQty(x.productId,1)} style={qty}>+</button></span></div>)}<div style={{fontWeight:700,borderTop:'1px solid #eee',paddingTop:10}}>الإجمالي: {total.toLocaleString('ar-EG')} ج</div><input placeholder="الاسم" value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})} style={input}/><input placeholder="الموبايل" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})} style={input}/><input placeholder="العنوان" value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})} style={input}/><button onClick={order} style={{...dark,width:'100%',justifyContent:'center'}}>تسجيل الطلب</button>{notice&&<div style={{fontSize:13,marginTop:8}}>{notice}</div>}</section></aside></div></div></main>
}
const panel:any={background:'#fff',border:'1px solid #e5e3dc',borderRadius:16,padding:18};const input:any={width:'100%',boxSizing:'border-box',border:'1px solid #ddd',borderRadius:10,padding:11,marginTop:8};const dark:any={background:'#111',color:'#fff',border:0,borderRadius:10,padding:'10px 13px',display:'inline-flex',alignItems:'center',gap:7,cursor:'pointer'};const qty:any={border:'1px solid #ddd',background:'#fff',borderRadius:6,padding:'1px 7px',marginRight:3,cursor:'pointer'};
