'use client';
import Link from 'next/link';
import { ArrowLeft, Bot, Check, MessageCircle, Package, Zap } from 'lucide-react';

export default function Offer(){
 const features=['AI موظف مبيعات عربي/إنجليزي','كتالوج منتجات وأسعار ومخزون حقيقي','تسجيل الطلبات وتحديث المخزون','لوحة تحكم للمبيعات والمنتجات','تركيب وتجهيز أولي مخصص لنشاطك','دعم وتعديلات بعد الإطلاق'];
 return <main dir="rtl" style={{minHeight:'100vh',background:'#f7f6f2',fontFamily:'Arial',color:'#151515'}}><header style={{maxWidth:1100,margin:'auto',padding:'24px',display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{fontWeight:800,fontSize:20}}>FlowSell <span style={{fontSize:12}}>AI</span></div><Link href="/" style={{color:'#111'}}>شوف الـ Demo ←</Link></header><section style={{maxWidth:1100,margin:'35px auto',padding:'20px',display:'grid',gridTemplateColumns:'1.25fr .75fr',gap:24,alignItems:'center'}}><div><div style={{display:'inline-flex',padding:'8px 12px',borderRadius:99,background:'#e9e9e2',fontSize:13}}>عرض إطلاق محدود للشركات الصغيرة</div><h1 style={{fontSize:'clamp(42px,6vw,72px)',lineHeight:1.02,margin:'18px 0'}}>خلي حد يرد على عملائك ويبيع <span style={{textDecoration:'underline'}}>24/7.</span></h1><p style={{fontSize:20,lineHeight:1.7,color:'#555',maxWidth:700}}>نركب لك موظف مبيعات بالذكاء الاصطناعي متصل بمنتجاتك وأسعارك ومخزونك، ويجمع الطلبات بدل ما تضيع المبيعات في الرسائل.</p><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:24}}><Link href="/assistant" style={button}>جرّبه بنفسك <ArrowLeft size={18}/></Link><Link href="/" style={{...button,background:'#fff',color:'#111',border:'1px solid #ddd'}}>شوف الـ Dashboard</Link></div></div><div style={card}><div style={{display:'flex',alignItems:'center',gap:10}}><div style={icon}><Bot size={20}/></div><div><b>FlowSell AI</b><div style={{fontSize:12,color:'#777'}}>Sales Agent</div></div></div><div style={{marginTop:20,padding:14,borderRadius:12,background:'#f1f1ec'}}>"السعر كام وهل متاح؟"</div><div style={{marginTop:8,padding:14,borderRadius:12,background:'#111',color:'#fff'}}>أيوه متاح ❤️ السعر 850 جنيه. تحب أسجل الطلب؟</div><div style={{display:'grid',gap:9,marginTop:20}}><div style={row}><MessageCircle size={17}/> رد فوري على العملاء</div><div style={row}><Package size={17}/> مخزون وأسعار حقيقية</div><div style={row}><Zap size={17}/> تسجيل الطلب تلقائيًا</div></div></div></section><section style={{maxWidth:1100,margin:'10px auto 80px',padding:'20px'}}><div style={{...card,padding:28}}><div style={{fontSize:13,color:'#777'}}>باقة الإطلاق</div><div style={{display:'flex',justifyContent:'space-between',gap:20,flexWrap:'wrap',alignItems:'end'}}><div><h2 style={{fontSize:36,margin:'8px 0'}}>2,500 جنيه</h2><p style={{color:'#666',margin:0}}>تركيب أولي + تخصيص حسب نشاطك</p></div><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(220px,1fr))',gap:10,flex:1}}>{features.map(f=><div key={f} style={row}><Check size={17}/> {f}</div>)}</div></div><div style={{marginTop:24,padding:14,borderRadius:12,background:'#f1f1ec',color:'#555'}}>بعد أول عميل ناجح نقدر نحولها لاشتراك شهري للدعم والتشغيل، بدل ما نبيع المشروع مرة واحدة فقط.</div></div></section></main>
}
const card:any={background:'#fff',border:'1px solid #e4e2db',borderRadius:20,padding:22,boxShadow:'0 10px 30px rgba(0,0,0,.04)'};const icon:any={width:42,height:42,borderRadius:12,background:'#111',color:'#fff',display:'grid',placeItems:'center'};const row:any={display:'flex',gap:8,alignItems:'center',padding:'8px 0',fontSize:14};const button:any={display:'inline-flex',alignItems:'center',gap:8,padding:'13px 17px',borderRadius:12,background:'#111',color:'#fff',textDecoration:'none',fontWeight:700};
